set -e

BINARY=$1
ARTIFACT_NAME=$2
OUTPUT_PATH=$3

GENERATED_SHA_256=$(shasum -a 256 $BINARY | awk '{print $1}')

mkdir $OUTPUT_PATH

cp $BINARY $OUTPUT_PATH/${ARTIFACT_NAME}
echo $GENERATED_SHA_256 > $OUTPUT_PATH/${ARTIFACT_NAME}.sha256
