addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml2-utils
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - oraclejdk8

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-installer-linux-x86_64.sh'
  - sha256sum -c .bazel-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.23.1-installer-linux-x86_64.sh
  - ./bazel-0.23.1-installer-linux-x86_64.sh --user
  - cp .bazelrc.travis .bazelrc
  - wget 'https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz'
  - tar -xf ghr_v0.12.0_linux_amd64.tar.gz
  - cp ghr_v0.12.0_linux_amd64/ghr $HOME/bin/

script:
  - bazel build //...
  - bazel test --test_output errors //...
  - bazel build src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar
  - ./gen_maven_deps.sh generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml
  - bazel run //:parse -- format-deps --overwrite --deps $PWD/dependencies.yaml
  - git diff --exit-code
  - bazel build //src/scala/com/github/johnynek/bazel_deps:parseproject_deploy.jar
  - tmp=$(mktemp -d) && cp bazel-bin/src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar $tmp && ghr -c $TRAVIS_COMMIT $(echo $TRAVIS_COMMIT | cut -b 1-8) $tmp
