addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml2-utils
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - oraclejdk8

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-linux-x86_64.sh'
  - sha256sum -c .bazel-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.2.3-installer-linux-x86_64.sh
  - ./bazel-0.2.3-installer-linux-x86_64.sh --user
  - cp .bazelrc.travis .bazelrc
  - cat ~/.bazelrc >> .bazelrc

script:
  - bazel build --strategy=Scalac=worker //...
  - bazel test --strategy=Scalac=worker //...
  - bazel build src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar
  - ./gen_maven_deps.sh `pwd` 3rdparty/workspace.bzl dependencies.yaml
  - git diff --exit-code
