addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml2-utils
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - openjdk11

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.25.2/bazel-0.25.2-installer-linux-x86_64.sh'
  - sha256sum -c .bazel-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.25.2-installer-linux-x86_64.sh
  - ./bazel-0.25.2-installer-linux-x86_64.sh --user
  - cp .bazelrc.travis .bazelrc

script:
  - bazel build //...
  - bazel test --test_output errors //...
  - bazel build src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar
  - ./gen_maven_deps.sh generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml
  - bazel run //:parse -- format-deps --overwrite --deps $PWD/dependencies.yaml
  - git diff --exit-code
