scala_test(name = "modeltest",
           srcs = ["ModelTest.scala"],
           deps = ["//src/scala/com/github/johnynek/bazel_deps:depsmodel"])

scala_test(name = "graphtest",
           srcs = ["GraphTest.scala"],
           deps = ["//src/scala/com/github/johnynek/bazel_deps:graph",
                   "//3rdparty/jvm/org/scalacheck"])
